#!/bin/bash

set -euo pipefail

# ==========================================================
# Data Completeness Report
# ==========================================================
# This script runs after the health check and produces a
# combined daily report for Telegram delivery.
# ==========================================================

PROJECT_DIR="/home/ubuntu/market-data-collector"
REPORT_DIR="$PROJECT_DIR/monitoring/health_reports"
HEALTH_SUMMARY_FILE="$PROJECT_DIR/monitoring/tmp_health_summary.txt"
COMBINED_REPORT_FILE="$REPORT_DIR/${REPORT_DATE:-$(date +"%Y-%m-%d")}_daily_report.txt"
REPORT_DATE=$(date +"%Y-%m-%d")

source "$PROJECT_DIR/utils/telegram.sh"

# ==========================================================
# Configuration
# ==========================================================
# This script expects the health summary file from the health
# check to exist. It also writes a combined report that includes
# the full health report and the full data completeness report.
# ==========================================================

mkdir -p "$REPORT_DIR"

# ==========================================================
# Health Summary
# ==========================================================
# Read the compact health summary generated by health_check.sh.
# ==========================================================

if [[ ! -f "$HEALTH_SUMMARY_FILE" ]]; then
    printf 'Collector=UNKNOWN\nDatabase=UNKNOWN\nBackup=UNKNOWN\nLogs=UNKNOWN\nDisk=UNKNOWN\nMemory=UNKNOWN\nCPU=UNKNOWN\nOverall=UNKNOWN\n' > "$HEALTH_SUMMARY_FILE"
fi

# ==========================================================
# Execute data quality report
# ==========================================================
# Run the existing Python report generator if available.
# The script preserves its current output while making it usable
# for the combined Telegram attachment.
# ==========================================================

DATA_REPORT_TMP="$REPORT_DIR/${REPORT_DATE}_data_quality_detail.txt"

if [[ -f "$PROJECT_DIR/reports/data_quality_report.py" ]]; then
    if ! "$PROJECT_DIR/venv/bin/python" "$PROJECT_DIR/reports/data_quality_report.py" > "$DATA_REPORT_TMP" 2>&1; then
        echo "ERROR: Data quality report generation failed" >&2
        exit 1
    fi
else
    cat > "$DATA_REPORT_TMP" <<'EOF'
Data quality report script not found.
EOF
fi

# ==========================================================
# Combined report assembly
# ==========================================================
# The attachment includes the detailed health output, the data
# quality output, and a summary block.
# ==========================================================

HEALTH_REPORT_FILE="$REPORT_DIR/${REPORT_DATE}_health_report.txt"
if [[ ! -f "$HEALTH_REPORT_FILE" ]]; then
    HEALTH_REPORT_FILE="$PROJECT_DIR/monitoring/health_report.txt"
fi

if [[ -f "$HEALTH_REPORT_FILE" ]]; then
    HEALTH_CONTENT=$(cat "$HEALTH_REPORT_FILE")
else
    HEALTH_CONTENT="Health report not found."
fi

if [[ -f "$DATA_REPORT_TMP" ]]; then
    DATA_CONTENT=$(cat "$DATA_REPORT_TMP")
else
    DATA_CONTENT="Data completeness report not found."
fi

# ==========================================================
# Parse summary values
# ==========================================================

parse_summary_value() {
    local key="$1"
    local file="$2"
    local value=""
    value=$(grep "^$key=" "$file" | head -n 1 | cut -d'=' -f2- || true)
    echo "$value"
}

format_status() {
    local status="$1"
    case "$status" in
        PASS|PASS\s*)
            echo "✅"
            ;;
        WARNING|WARN|WARN\s*)
            echo "⚠"
            ;;
        FAIL|FAIL\s*)
            echo "❌"
            ;;
        *)
            echo "❓"
            ;;
    esac
}

get_index_status() {
    local index="$1"
    local file="$2"

    awk -v idx="$index" '
        $0 == idx { in_block = 1; next }
        in_block && $0 ~ /Overall Status/ {
            print $NF
            exit
        }
    ' "$file"
}

get_summary_value() {
    local label="$1"
    local file="$2"

    awk -v label="$label" '
        /^SUMMARY$/ { in_summary = 1; next }
        in_summary && $0 ~ label {
            sub(/^.*: /, "", $0)
            print $0
            exit
        }
    ' "$file"
}

COLLECTOR_VALUE=$(parse_summary_value "Collector" "$HEALTH_SUMMARY_FILE")
DATABASE_VALUE=$(parse_summary_value "Database" "$HEALTH_SUMMARY_FILE")
BACKUP_VALUE=$(parse_summary_value "Backup" "$HEALTH_SUMMARY_FILE")
LOGS_VALUE=$(parse_summary_value "Logs" "$HEALTH_SUMMARY_FILE")
DISK_VALUE=$(parse_summary_value "Disk" "$HEALTH_SUMMARY_FILE")
MEMORY_VALUE=$(parse_summary_value "Memory" "$HEALTH_SUMMARY_FILE")
CPU_VALUE=$(parse_summary_value "CPU" "$HEALTH_SUMMARY_FILE")
OVERALL_HEALTH=$(parse_summary_value "Overall" "$HEALTH_SUMMARY_FILE")

DATA_QUALITY_STATUS=$(get_summary_value "Overall Status" "$DATA_REPORT_TMP")
EXPECTED_ROWS=$(get_summary_value "Expected Rows" "$DATA_REPORT_TMP")
ACTUAL_ROWS=$(get_summary_value "Actual Rows" "$DATA_REPORT_TMP")
MISSING_ROWS=$(get_summary_value "Missing Rows" "$DATA_REPORT_TMP")
DUPLICATE_ROWS=$(get_summary_value "Duplicate Rows" "$DATA_REPORT_TMP")
NULL_VALUES=$(get_summary_value "NULL Values" "$DATA_REPORT_TMP")

if [[ -z "$DATA_QUALITY_STATUS" ]]; then
    DATA_QUALITY_STATUS="PASS"
fi

INDEX_LINES=""
for index in NIFTY BANKNIFTY FINNIFTY SENSEX; do
    index_status=$(get_index_status "$index" "$DATA_REPORT_TMP")
    if [[ -z "$index_status" ]]; then
        index_status="UNKNOWN"
    fi

    if [[ -n "$INDEX_LINES" ]]; then
        INDEX_LINES+=$'\n'
    fi

    INDEX_LINES+=$(printf '%-14s %s' "$index" "$(format_status "$index_status")")
done

# ==========================================================
# Telegram message
# ==========================================================

MESSAGE=$(cat <<EOF
📊 *MARKET DATA DAILY REPORT*

📅 Date : $REPORT_DATE

Health

Collector        $(format_status "$COLLECTOR_VALUE")
Database         $(format_status "$DATABASE_VALUE")
Backup           $(format_status "$BACKUP_VALUE")
Logs             $(format_status "$LOGS_VALUE")
Disk             $DISK_VALUE
Memory           $MEMORY_VALUE
CPU              $(format_status "$CPU_VALUE")

Overall Health
$(format_status "$OVERALL_HEALTH")

------------------------------------

Data Quality

$INDEX_LINES

Expected Rows    $EXPECTED_ROWS
Actual Rows      $ACTUAL_ROWS
Missing Rows     $MISSING_ROWS
Duplicate Rows   $DUPLICATE_ROWS
NULL Values      $NULL_VALUES

Overall Data
$(format_status "$DATA_QUALITY_STATUS")
EOF
)

# ==========================================================
# Write combined attachment
# ==========================================================

{
    echo "------------------------------------------"
    echo "HEALTH REPORT"
    echo "------------------------------------------"
    echo "$HEALTH_CONTENT"
    echo ""
    echo "------------------------------------------"
    echo "DATA QUALITY REPORT"
    echo "------------------------------------------"
    echo "$DATA_CONTENT"
    echo ""
    echo "------------------------------------------"
    echo "SUMMARY"
    echo "------------------------------------------"
    echo "Overall Health : $OVERALL_HEALTH"
    echo "Overall Data Quality : $DATA_QUALITY_STATUS"
} > "$COMBINED_REPORT_FILE"

# ==========================================================
# Telegram delivery
# ==========================================================
# Telegram errors are non-fatal and only produce a warning.
# ==========================================================

if ! send_telegram_message "$MESSAGE"; then
    echo "WARNING: Failed to send Telegram message" >&2
fi

if ! send_telegram_document "$COMBINED_REPORT_FILE" "Daily Market Data Report"; then
    echo "WARNING: Failed to send Telegram attachment" >&2
fi

exit 0
